name: phpstan

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
        with:
          args: --ignore-platform-reqs
      - uses: php-actions/phpstan@v3
        with:
          path: src/
